version: 2

updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "rsc.io/qr"
        update-types: ["version-update:semver-minor"]
  - package-ecosystem: "gomod"
    directory: "/nested_go"
    schedule:
      interval: "daily"
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "com.google.inject:guice"
        update-types: ["version-update:semver-major"]
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "org.apache.httpcomponents:httpclient"
        update-types: ["version-update:semver-patch"]
  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "dependabot-test"
        versions: [">= 0"]
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "rust"
        update-types: ["version-update:semver-minor"]
  - package-ecosystem: "mix"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "phoenix"
        update-types: ["version-update:semver-patch"]
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "rubocop"
        update-types: ["version-update:semver-major"]
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "phpmailer/phpmailer"
        update-types: ["version-update:semver-major"]
  - package-ecosystem: "elm"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "elm/svg"
        update-types: ["version-update:semver-patch"]
  - package-ecosystem: "terraform"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "github_ssh_without_protocol"
        update-types: ["version-update:semver-minor"]
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
